# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string


pool:
  name: ci-runner-gpu
# pool:
#   vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    # sudo apt -y update
    # sudo apt -y install python3-setuptools python3-wheel
    # sudo usermod -a -G render,video $LOGNAME
    # sudo apt -y install "linux-headers-$(uname -r)" "linux-modules-extra-$(uname -r)"
    # sudo lspci -d 1002:7461
    sudo apt update
    sudo apt install "linux-headers-$(uname -r)" "linux-modules-extra-$(uname -r)"
    sudo apt install python3-setuptools python3-wheel
    sudo usermod -a -G render,video $LOGNAME # Add the current user to the render and video groups
    wget https://repo.radeon.com/amdgpu-install/6.3.3/ubuntu/noble/amdgpu-install_6.3.60303-1_all.deb
    sudo apt install ./amdgpu-install_6.3.60303-1_all.deb
    sudo apt update
    sudo apt install amdgpu-dkms rocm

  displayName: 'Install ROCm drivers'
