# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - none

pool:
  name: ci-pool

container:
  image: ubuntu:24.04
  # image: ghcr.io/ukri-bench/spack-buildcache-img:17f76d16f9e4d633293b837c71fcc54ef93d6e1b
  # endpoint: ghcr-io

variables:
- name: sha

# parameters:
# - name: "sha"
#   # displayName: "Git sha"  # the human-readable name shown in the Azure DevOps UI. optional, default is same as name
#   type: string # see more below. required
#   default: 'foo'
#   # values: # including this creates a dropdown box allowing you to select 1 of the options
#   # - 'first allowed value'
#   # - 'second allowed value'

steps:
- script: echo $(sha)
- script: echo ${{ variables['sha'] }}
- script: echo ${{ variables.sha }}
- script: echo ${{ parameters.sha }}
# - script: echo ${{ parameters['sha'] }}

- script: echo Hello, world!
  displayName: 'Run a one-line script'

# - script: |
#     bench_dolfinx --ndofs=1000 --degree=3 --qmode=0 --nreps=1 --mat_comp --float=64 --json a.json
#   displayName: 'Run benchmark (serial)'

# - script: |
#     mpirun -n 2 bench_dolfinx --ndofs=500 --degree=3 --qmode=0 --nreps=1 --mat_comp --float=64 --json b.json
#   displayName: 'Run benchmark (MPI parallel)'

# - script: |
#     python src/test_output.py a.json
#     python src/test_output.py b.json
#   displayName: 'Post-process'
