# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: ukri-ci-runners
  # vmImage: ukri-ci-runners

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    git clone --depth 1 https://github.com/spack/spack.git
  displayName: 'Get Spack'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    ls -alh
  displayName: 'Run a multi-line script'
