name: Test  Azure
on:
  # Uncomment the below 'push' to trigger on push
  push:
    branches:
      - "**"
  # pull_request:
  #   branches: [ "main" ]
  # merge_group:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  Hello-World-Job:
    # runs-on:
    #   - codebuild-ukri-bench-${{ github.run_id }}-${{ github.run_attempt }}
    runs-on: "cirun-azure-runner--${{ github.run_id }}"
  # runs-on:
  #     - codebuild-ukri-bench-${{ github.run_id }}-${{ github.run_attempt }}
  #       instance-size:gpu_small
  #     # image:<environment-type>-<image-identifier>

    steps:

    - name: Test
      run: |
        echo "Hello World"
