name: Configure and build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:nightly

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        df -h
        apt-get update
        apt-get -y install rsync wget python3-setuptools python3-wheel libboost-program-options-dev
        wget https://repo.radeon.com/amdgpu-install/6.3.3/ubuntu/noble/amdgpu-install_6.3.60303-1_all.deb
        apt -y install ./amdgpu-install_6.3.60303-1_all.deb
        DEBIAN_FRONTEND=noninteractive amdgpu-install --accept-eula -y --usecase=rocmdev --no-dkms
        apt-get -y install rocthrust
        ls /opt/rocm/bin

    - run: |
        PATH=$PATH:/opt/rocm/bin:/opt/rocm/rocprofiler/bin:/opt/rocm/hip/bin
        LD_LIBRARY_PATH=/opt/rocm/lib:/opt/rocm/llvm/lib:/opt/rocm/hip/lib
        hipcc --help

    - name: Configure CMake
      run: |
        PATH=$PATH:/opt/rocm/bin:/opt/rocm/rocprofiler/bin:/opt/rocm/hip/bin
        LD_LIBRARY_PATH=/opt/rocm/lib:/opt/rocm/llvm/lib:/opt/rocm/hip/lib
        cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DHIP_ARCH=gfx90a

    - name: Build
      run: |
        PATH=$PATH:/opt/rocm/bin:/opt/rocm/rocprofiler/bin:/opt/rocm/hip/bin
        LD_LIBRARY_PATH=/opt/rocm/lib:/opt/rocm/llvm/lib:/opt/rocm/hip/lib
        cmake --build build --config ${{env.BUILD_TYPE}}
