name: Lint

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches:
      - main
  workflow_dispatch:


jobs:
  doc-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mattnotmitt/doxygen-action@v1.12
    - name: Doxygen check
      run: |
        cd src
        doxygen
