name: CPU run

on:
  workflow_call:
    # inputs:
    #   tag:
    #     required: true
    #     type: string
    # secrets:
    #   token:
    #     required: true

env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  run-code:
    name: Run code
    runs-on: ubuntu-latest
    container: ghcr.io/ukri-bench/spack-buildcache-img:${{ inputs.tag }}
    # container:
    #   image: ghcr.io/ukri-bench/spack-buildcache-img:${{ inputs.tag }}
    #   credentials:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.github_token }}

    env:
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe

    steps:
      - name: Install (CPU)
        run: |
          ls -alh
          echo "Running triggered (1): ${{ github.sha }}"

      - name: Install (CPU, failed)
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          ls -alh
          echo "Running triggered (2): ${{ github.sha }}"
