name: CPU run

on:
  workflow_run:
    workflows: ["Spack build and run"]
    types: [requested]

env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  run-code:
    name: Run code
    runs-on: ubuntu-latest
    container: ghcr.io/ukri-bench/spack-buildcache-img${{ github.sha }}

    steps:
      - name: Install (CPU)
        run: |
          ls -alh
          echo "view"
          ls /opt/view