name: CPU run

on:
  # workflow_run:
  #   workflows:
  #     - Spack build and run
  #   types:
  #     - completed
  workflow_dispatch:


# on:
#   workflow_run:
#     workflows: ["Spack build and run"]
#     types:
#       - completed
#     # types: [requested]

# env:
#   GITHUB_USER: ${{ github.actor }}
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  run-code:
    name: Run code
    runs-on: ubuntu-latest
    # container: ghcr.io/ukri-bench/spack-buildcache-img:${{ github.sha }}
    # container: ubuntu:24.04
    container:
      image: ghcr.io/ukri-bench/spack-buildcache-img:a3c92f44aff2b04590dfd12c8dc6ab80d1225925
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: Install (CPU)
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          ls -alh
          echo "Running triggered (1): ${{ github.sha }}"

      - name: Install (CPU, failed)
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          ls -alh
          echo "Running triggered (2): ${{ github.sha }}"
