name: CPU run

on:
<<<<<<< HEAD
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
=======
  workflow_run:
    workflows:
      - Spack build and run
    types:
      - completed
  workflow_dispatch:


# on:
#   workflow_run:
#     workflows: ["Spack build and run"]
#     types:
#       - completed
#     # types: [requested]

# env:
#   GITHUB_USER: ${{ github.actor }}
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

>>>>>>> origin/main
jobs:
  run-code:
    name: Run code
    runs-on: ubuntu-latest
<<<<<<< HEAD
    container: ghcr.io/ukri-bench/spack-buildcache-img:${{ inputs.tag }}
    env:
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe
=======
    # container: ghcr.io/ukri-bench/spack-buildcache-img${{ github.sha }}
    # container: ubuntu:24.04
    container:
      image: ghcr.io/ukri-bench/spack-buildcache-img
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

>>>>>>> origin/main
    steps:
      - uses: actions/checkout@v4  # To get post-processing script
      - name: Run (CPU)
        run: |
<<<<<<< HEAD
          bench_dolfinx --ndofs=1000 --degree=3 --qmode=0 --nreps=1 --mat_comp --float=64 --json a.json
          mpirun -n 2 bench_dolfinx --ndofs=500 --degree=3 --qmode=0 --nreps=1 --mat_comp --float=64 --json b.json
      - name: Post-process
        run: |
          python src/test_output.py a.json
          python src/test_output.py b.json
=======
          ls -alh
          echo "Running triggered: ${{ github.sha }}""
>>>>>>> origin/main
