name: Spack build

on:
  # Uncomment the below 'push' to trigger on push
  push:
   branches:
     - "**"
  # schedule:
  #   # '*' is a special character in YAML, so string must be quoted
  #   - cron: "0 2 * * THU"
  workflow_dispatch:

env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_cuda:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Make space on disk
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo apt-get remove -y '^aspnetcore-.*' '^dotnet-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli google-chrome-stable firefox powershell mono-devel

      # - name: Free Disk Space (Ubuntu)
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     # this might remove tools that are actually needed,
      #     # if set to "true" but frees about 6 GB
      #     tool-cache: false

      - uses: actions/checkout@v4

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop        # Spack version (examples: develop, releases/v0.23)
          color: true         # Force color output (SPACK_COLOR=always)
          path: spack-src     # Where to clone Spack      # - name: Get Spack

      - name: Install
        shell: spack-bash {0}
        run: |
          spack -e . repo add ./spack
          spack -e . install -v -j 6 --fail-fast

      - name: Push packages and update index
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: spack -e . buildcache push --base-image ubuntu:24.04 --update-index local-buildcache
        if: ${{ !cancelled() }}
