name: Spack build

on:
  # Uncomment the below 'push' to trigger on push
  push:
   branches:
     - "**"
  # schedule:
  #   # '*' is a special character in YAML, so string must be quoted
  #   - cron: "0 2 * * THU"
  workflow_dispatch:

env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # build_cuda:
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     packages: write
  #   steps:
  #     - name: Make space on disk
  #       run: |
  #         sudo rm -rf /usr/local/lib/android
  #         sudo rm -rf /opt/ghc
  #         sudo rm -rf /usr/local/.ghcup
  #         sudo apt-get remove -y '^aspnetcore-.*' '^dotnet-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli google-chrome-stable firefox powershell mono-devel

  #     - uses: actions/checkout@v4

  #     - name: Set up Spack
  #       uses: spack/setup-spack@v2
  #       with:
  #         ref: develop        # Spack version (examples: develop, releases/v0.23)
  #         color: true         # Force color output (SPACK_COLOR=always)
  #         path: spack-src     # Where to clone Spack      # - name: Get Spack

  #     - name: Install
  #       shell: spack-bash {0}
  #       run: |
  #         spack -e . repo add ./spack
  #         spack -e . install -v -j 6 --fail-fast

  #     - name: Push packages and update index
  #       env:
  #         GITHUB_USER: ${{ github.actor }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       run: spack -e . buildcache push --base-image ubuntu:24.04 --update-index local-buildcache
  #       if: ${{ !cancelled() }}

  build_rocm:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      # - name: Make space on disk
      #   run: |
      #     sudo rm -rf /usr/local/lib/android
      #     sudo rm -rf /opt/ghc
      #     sudo rm -rf /usr/local/.ghcup
      #     sudo apt-get remove -y '^aspnetcore-.*' '^dotnet-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli google-chrome-stable firefox powershell mono-devel

      - name: Install rocm
        run: |
          wget https://repo.radeon.com/amdgpu-install/6.3.3/ubuntu/noble/amdgpu-install_6.3.60303-1_all.deb
          sudo apt-get install ./amdgpu-install_6.3.60303-1_all.deb
          sudo apt-get update
          sudo apt-get install python3-setuptools python3-wheel
          DEBIAN_FRONTEND=noninteractive amdgpu-install --accept-eula -y --usecase=rocmdev --no-dkms
          sudo apt-get install hipcc rocm-core rocthrust

      - uses: actions/checkout@v4

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop        # Spack version (examples: develop, releases/v0.23)
          color: true         # Force color output (SPACK_COLOR=always)
          path: spack-src     # Where to clone Spack      # - name: Get Spack

      - name: Install
        shell: spack-bash {0}
        run: |
          spack -e . install -j 4 bench-dolfinx+rocm amdgpu_target=gfx90a

      # - name: Push packages and update index
      #   env:
      #     GITHUB_USER: ${{ github.actor }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: spack -e . buildcache push --base-image ubuntu:24.04 --update-index local-buildcache
      #   if: ${{ !cancelled() }}
