name: Spack build

on:
  # Uncomment the below 'push' to trigger on push
  # push:
  #  branches:
  #    - "**"
  # schedule:
  #   # '*' is a special character in YAML, so string must be quoted
  #   - cron: "0 2 * * THU"
  workflow_dispatch:
    # inputs:
    #   spack_repo:
    #     description: "Spack repository to test"
    #     default: "spack/spack"
    #     type: string
    #   spack_ref:
    #     description: "Spack repository branch/tag to test"
    #     default: "develop"
    #     type: string
    #   dolfinx_version:
    #     description: "DOLFINx release branch/tag to test"
    #     default: "0.9.0"
    #     type: string

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    # container: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4

      # - name: Install Spack requirements
      #   run: |
      #     apt-get -y update
      #     apt-get install -y bzip2 curl file git gzip make patch python3-minimal tar unzip xz-utils
      #     apt-get install -y g++ gfortran  # compilers
      # - name: Get Spack
      #   uses: actions/checkout@v4
      #   with:
      #     path: ./spack-src
      #     repository: spack/spack

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop # Spack version (examples: develop, releases/v0.23)
          buildcache: true    # Configure oci://ghcr.io/spack/github-actions-buildcache
          color: true         # Force color output (SPACK_COLOR=always)
          path: spack-src         # Where to clone Spack      # - name: Get Spack

      # . ./spack-src/share/spack/setup-env.sh

      # - name: Build (HIP)
      #   shell: spack-bash {0}
      #   run: |
      #     spack env create bench-ci
      #     spack env activate bench-ci
      #     spack repo add ./spack
      #     spack add bench-dolfinx+rocm amdgpu_target=gfx90a
      #     spack -v install -j 4 --fail-fast

      - name: Build (CUDA)
        shell: spack-bash {0}
        run: spack -e . install
        # run: |
        #   spack env create bench-ci
        #   spack env activate bench-ci
        #   spack repo add ./spack
        #   spack add bench-dolfinx+cuda cuda_arch=80
        #   spack -v install -j 4 --fail-fast

      - name: Run
        shell: spack-bash {0}
        run: |
          spack env activate .
          python3 -c 'print("hello world")'

      - name: Push packages and update index
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: spack -e . buildcache push --base-image ubuntu:24.04 --update-index local-buildcache
        if: ${{ !cancelled() }}
