name: Spack build and run

# Build a version of the benchmark code using the Spack spec. Executes
# the CPU benchmark version.

on:
  # Uncomment the below 'push' to trigger on push
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches:
      - main
  # schedule:
  #   # '*' is a special character in YAML, so string must be quoted
  #   - cron: "0 2 * * THU"
  workflow_dispatch:

env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build benchmark code
    strategy:
      matrix:
        backend:
          [
            { device: cpu, spack_opt: "@main~cuda~rocm" },
            { device: rocm, spack_opt: "@main+rocm amdgpu_target=gfx90a" },
            { device: cuda, spack_opt: "@main+cuda cuda_arch=80" },
          ]
    runs-on: ubuntu-24.04
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - if: ${{ matrix.backend.device != 'cpu' }}
        name: Install GPU compiler/driver
        uses: ukri-bench/spack-configs/actions/install-gpu-driver@main
        with:
          runtime: ${{ matrix.backend.device }}

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop    # Spack version (examples: develop, releases/v0.23)
          color: true     # Force color output (SPACK_COLOR=always)
          path: spack-src # Where to clone Spack      # - name: Get Spack

      - if: ${{ matrix.backend.device == 'cpu' }}
        name: Get Spack config (CPU)
        run: |
          wget -O spack.yml https://raw.githubusercontent.com/ukri-bench/spack-configs/refs/heads/main/configs/gh-actions/spack.yml
      - if: ${{ matrix.backend.device != 'cpu' }}
        name: Get Spack config (GPU)
        run: |
          wget -O spack.yml https://raw.githubusercontent.com/ukri-bench/spack-configs/refs/heads/main/configs/gh-actions/spack-${{ matrix.backend.device }}.yml

      - if: ${{ matrix.backend.device == 'rocm' }}
        name: Find compilers (ROCm)
        shell: spack-bash {0}
        run: spack compiler find

      - name: Add ukri-bench Spack repository and create environment
        shell: spack-bash {0}
        run: |
          spack repo add --name bench_pkgs https://github.com/ukri-bench/spack-packages.git ./bench_pkgs
          spack mirror add --unsigned --type binary --oci-username-variable GITHUB_USER --oci-password-variable GITHUB_TOKEN local-buildcache oci://ghcr.io/ukri-bench/spack-buildcache
          spack env create . spack.yml

      - name: Install benchmark
        shell: spack-bash {0}
        run: |
          spack -e . install -U -j 4 --use-buildcache=package:never,dependencies:auto --add py-numpy bench-dolfinx${{ matrix.backend.spack_opt }}

      - name: Push test image (CPU)
        if: ${{ matrix.backend.device == 'cpu' }}
        shell: spack-bash {0}
        run: |
          spack -e . mirror add --unsigned --type binary --oci-username-variable GITHUB_USER \
            --oci-password-variable GITHUB_TOKEN local-buildcache-img \
            oci://ghcr.io/ukri-bench/spack-buildcache-img
          spack -e . buildcache push --base-image ubuntu:24.04 --update-index \
            --tag ${{ github.sha }} local-buildcache-img

      - name: Push test image (CUDA)
        if: ${{ matrix.backend.device == 'cuda' }}
        shell: spack-bash {0}
        run: |
          spack -e . mirror add --unsigned --type binary --oci-username-variable GITHUB_USER \
            --oci-password-variable GITHUB_TOKEN local-buildcache-cuda \
            oci://ghcr.io/ukri-bench/spack-buildcache-cuda
          spack -e . buildcache push --base-image ubuntu:24.04 --update-index \
            --tag ${{ github.sha }} local-buildcache-cuda

      - name: Push packages and update index
        shell: spack-bash {0}
        run: |
          spack -e . buildcache push --base-image ubuntu:24.04 --only dependencies \
            --with-build-dependencies --update-index local-buildcache
        if: ${{ !cancelled() }}

  run-code:
    name: Run benchmark code (CPU)
    needs: build
    runs-on: ubuntu-latest
    container: ghcr.io/ukri-bench/spack-buildcache-img:${{ github.sha }}
    env:
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe
    steps:
      - uses: actions/checkout@v4  # To get post-processing script
      - name: Run (CPU)
        run: |
          bench_dolfinx --ndofs=1000 --degree=3 --qmode=0 --nreps=1 --mat_comp --float=64 --json a.json
          mpirun -n 2 bench_dolfinx --ndofs=500 --degree=3 --qmode=0 --nreps=1 --mat_comp --float=64 --json b.json
      - name: Post-process
        run: |
          python src/test_output.py a.json
          python src/test_output.py b.json

  # run-code-aws:
  #   name: Run benchmark code on AWS CodeBuild
  #   needs: build
  #   runs-on:
  #     - codebuild-ukri-bench-${{ github.run_id }}-${{ github.run_attempt }}
  #       # instance-size:small
  #   container:
  #     image: ghcr.io/ukri-bench/spack-buildcache-img:${{ github.sha }}
  #     credentials:
  #       username: ${{ github.actor }}
  #       password: ${{ secrets.github_token }}

  #   env:
  #     OMPI_ALLOW_RUN_AS_ROOT: 1
  #     OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  #     PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe

  #   steps:
  #     - uses: actions/checkout@v4  # To get post-processing script

  #     - name: Run (CPU)
  #       run: |
  #         bench_dolfinx --ndofs=1000 --degree=3 --qmode=0 --nreps=1 --mat_comp --float=64 --json a.json
  #         mpirun -n 2 bench_dolfinx --ndofs=500 --degree=3 --qmode=0 --nreps=1 --mat_comp --float=64 --json b.json

  #     - name: Post-process
  #       run: |
  #         python src/test_output.py a.json
  #         python src/test_output.py b.json

  run-code-aws:
    name: Run benchmark code on AWS GPU
    # needs: build
    runs-on:
      - codebuild-ukri-bench-${{ github.run_id }}-${{ github.run_attempt }}
        instance-size:gpu1.small
    # container:
    #   image: ghcr.io/ukri-bench/spack-buildcache-img:${{ github.sha }}
    #   credentials:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.github_token }}

    # env:
    #   OMPI_ALLOW_RUN_AS_ROOT: 1
    #   OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
    #   PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe

    steps:
      - uses: actions/checkout@v4  # To get post-processing script

      - name: Run (CPU)
        run:  nvidia-smi
      #     bench_dolfinx --ndofs=1000 --degree=3 --qmode=0 --nreps=1 --mat_comp --float=64 --json a.json
      #     mpirun -n 2 bench_dolfinx --ndofs=500 --degree=3 --qmode=0 --nreps=1 --mat_comp --float=64 --json b.json

      # - name: Post-process
      #   run: |
      #     python src/test_output.py a.json
      #     python src/test_output.py b.json


  # run-code-azure:
  #   name: Run benchmark code on Azure Pipelines
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   # - uses: Azure/pipelines@v1.2
  #   - uses: tjcorr/pipelines@v1.4
  #     with:
  #       azure-devops-project-url: 'https://dev.azure.com/ukribench/benchmark-dolfinx'
  #       azure-pipeline-name: 'ukri-bench.benchmark-dolfinx'  # name of the Azure pipeline to be triggered
  #       azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  #       azure-pipeline-variables: '{"SHA": "${{ github.sha }}"}'

  # run-cpu-reuable:
  #   name: Run benchmark code (CPU, reusable)
  #   needs: build
  #   uses: ./.github/workflows/run_cpu.yml
  #   with:
  #     tag: ${{ github.sha }}
