name: Spack build

on:
  # Uncomment the below 'push' to trigger on push
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches:
      - main
  # schedule:
  #   # '*' is a special character in YAML, so string must be quoted
  #   - cron: "0 2 * * THU"
  workflow_dispatch:

env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        backend:
          [
            # { runtime: cpu, driver: ''},
            { runtime: rocm, driver: amdgpu_target=gfx90a },
            # { runtime: cuda, driver: cuda_arch=80 },
          ]
    runs-on: ubuntu-24.04
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Install rocm
        if: ${{ matrix.backend.runtime == 'rocm' }}
        # uses: ukri-bench/benchmark-dolfinx/.github/workflows/rocm@actions-rocm
        uses: .github/workflows/rocm
        # run: |
        #   wget https://repo.radeon.com/amdgpu-install/6.3.3/ubuntu/noble/amdgpu-install_6.3.60303-1_all.deb
        #   sudo apt-get install ./amdgpu-install_6.3.60303-1_all.deb
        #   sudo apt-get update
        #   sudo apt-get install python3-setuptools python3-wheel
        #   DEBIAN_FRONTEND=noninteractive amdgpu-install --accept-eula -y --usecase=rocmdev --no-dkms
        #   sudo apt-get install hipcc rocm-core rocthrust

      # - name: Install CUDA
      #   if: ${{ matrix.backend.runtime == 'cuda' }}
      #   run: |
      #     wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
      #     sudo dpkg -i cuda-keyring_1.1-1_all.deb
      #     sudo apt-get update
      #     sudo apt-get -y install cuda-compiler-12-9


      # - name: Set up Spack
      #   uses: spack/setup-spack@v2
      #   with:
      #     ref: develop # Spack version (examples: develop, releases/v0.23)
      #     color: true # Force color output (SPACK_COLOR=always)
      #     path: spack-src # Where to clone Spack      # - name: Get Spack

      # - name: Install (CPU)
      #   if: ${{ matrix.backend.runtime != 'cuda' && matrix.backend.runtime != 'rocm' }}
      #   shell: spack-bash {0}
      #   run: |
      #     spack repo add --name bench_pkgs https://github.com/ukri-bench/spack-packages.git bench_pkgs
      #     spack env create . spack-configs/gh-actions-env.yaml
      #     spack -e . install -j 4 --use-buildcache=package:never,dependencies:auto --add bench-dolfinx

      # - name: Install (GPU)
      #   if: ${{ matrix.backend.runtime == 'cuda' || matrix.backend.runtime == 'rocm' }}
      #   shell: spack-bash {0}
      #   run: |
      #     spack repo add --name bench_pkgs https://github.com/ukri-bench/spack-packages.git bench_pkgs
      #     spack env create . spack-configs/gh-actions-env.yaml
      #     spack -e . install -j 4 --use-buildcache=package:never,dependencies:auto --add bench-dolfinx+${{ matrix.backend.runtime }} ${{ matrix.backend.driver }}

      # - name: Push packages and update index
      #   env:
      #     GITHUB_USER: ${{ github.actor }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: spack -e . buildcache push --base-image ubuntu:24.04 --update-index local-buildcache
      #   if: ${{ !cancelled() }}
