name: Spack build

on:
  # Uncomment the below 'push' to trigger on push
  # push:
  #  branches:
  #    - "**"
  # schedule:
  #   # '*' is a special character in YAML, so string must be quoted
  #   - cron: "0 2 * * THU"
  workflow_dispatch:
    # inputs:
    #   spack_repo:
    #     description: "Spack repository to test"
    #     default: "spack/spack"
    #     type: string
    #   spack_ref:
    #     description: "Spack repository branch/tag to test"
    #     default: "develop"
    #     type: string
    #   dolfinx_version:
    #     description: "DOLFINx release branch/tag to test"
    #     default: "0.9.0"
    #     type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:24.04

    # env:
    #   OMPI_ALLOW_RUN_AS_ROOT: 1
    #   OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
    #   PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe   # Newer OpenMPI
    #   OMPI_MCA_rmaps_base_oversubscribe: true                 # Older OpenMPI

    #   DOLFINX_RELEASE_VERSION: "${{ github.event_name != 'workflow_dispatch' && '0.9.0' || github.event.inputs.dolfinx_version }}"

    steps:
      - uses: actions/checkout@v4

      - name: Install Spack requirements
        run: |
          apt-get -y update
          apt-get install -y bzip2 curl file git gzip make patch python3-minimal tar unzip xz-utils
          apt-get install -y g++ gfortran  # compilers

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop # Spack version (examples: develop, releases/v0.23)
          buildcache: true    # Configure oci://ghcr.io/spack/github-actions-buildcache
          color: true         # Force color output (SPACK_COLOR=always)
          path: spack-src         # Where to clone Spack      # - name: Get Spack
      #   uses: actions/checkout@v4
      #   with:
      #     path: ./spack-package
      #     repository: spack/spack

      - name: Debug list
        run: |
          echo "Check files"
          ls -alh
          echo "Check files (1)"
          ls -alh ../

      - name: Build
        shell: spack-bash {0}
        run: |
          spack env create bench-ci
          spack env activate bench-ci
          spack repo add ./spack
          spack add bench-dolfinx+cuda cuda_arch=80
          spack install -j 4
