name: Spack build

on:
  # Uncomment the below 'push' to trigger on push
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches:
      - main
  # schedule:
  #   # '*' is a special character in YAML, so string must be quoted
  #   - cron: "0 2 * * THU"
  workflow_dispatch:

env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        backend:
          [
            { runtime: cpu, driver: ''},
            { runtime: rocm, driver: amdgpu_target=gfx90a },
            { runtime: cuda, driver: cuda_arch=80 },
          ]
    runs-on: ubuntu-24.04
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Install rocm
        if: ${{ matrix.backend.runtime == 'rocm' }}
        uses: spack-configs/actions/rocm@main

      # # - name: Get CUDA
      # #   if: ${{ matrix.backend.runtime == 'cuda' }}
      # #   uses: Jimver/cuda-toolkit@v0.2.26
      # #   # id: cuda-toolkit
      # #   # with:
      # #   #   cuda: '12.9.1'

      # - name: Install CUDA
      #   if: ${{ matrix.backend.runtime == 'cuda' }}
      #   uses: ukri-bench/spack-configs/actions/cuda@main

      # - name: Set up Spack
      #   uses: spack/setup-spack@v2
      #   with:
      #     ref: develop # Spack version (examples: develop, releases/v0.23)
      #     color: true # Force color output (SPACK_COLOR=always)
      #     path: spack-src # Where to clone Spack      # - name: Get Spack

      # - name: Install (CPU)
      #   if: ${{ matrix.backend.runtime != 'cuda' && matrix.backend.runtime != 'rocm' }}
      #   shell: spack-bash {0}
      #   run: |
      #     spack repo add --name bench_pkgs https://github.com/ukri-bench/spack-packages.git bench_pkgs
      #     spack env create . spack-configs/gh-actions-env.yaml
      #     spack -e . install -j 4 --use-buildcache=package:never,dependencies:auto --add bench-dolfinx

      # - name: Install (GPU)
      #   if: ${{ matrix.backend.runtime == 'cuda' || matrix.backend.runtime == 'rocm' }}
      #   shell: spack-bash {0}
      #   run: |
      #     spack repo add --name bench_pkgs https://github.com/ukri-bench/spack-packages.git bench_pkgs
      #     spack env create . spack-configs/gh-actions-env.yaml
      #     spack -e . install -j 4 --use-buildcache=package:never,dependencies:auto --add bench-dolfinx+${{ matrix.backend.runtime }} ${{ matrix.backend.driver }}

      # - name: Push packages and update index
      #   env:
      #     GITHUB_USER: ${{ github.actor }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: spack -e . buildcache push --base-image ubuntu:24.04 --update-index local-buildcache
      #   if: ${{ !cancelled() }}
