name: Spack build

on:
  # Uncomment the below 'push' to trigger on push
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches:
      - main
  # schedule:
  #   # '*' is a special character in YAML, so string must be quoted
  #   - cron: "0 2 * * THU"
  workflow_dispatch:

env:
  GITHUB_USER: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        backend:
          [
            { runtime: cpu, driver: ''},
            { runtime: rocm, driver: amdgpu_target=gfx90a },
            { runtime: cuda, driver: cuda_arch=80 },
          ]
    runs-on: ubuntu-24.04
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - if: ${{ matrix.backend.runtime == 'rocm' }}
        name: Install rocm
        uses: ukri-bench/spack-configs/actions/rocm@main

      - if: ${{ matrix.backend.runtime == 'cuda' }}
        name: Install CUDA
        uses: ukri-bench/spack-configs/actions/cuda@main

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop # Spack version (examples: develop, releases/v0.23)
          color: true # Force color output (SPACK_COLOR=always)
          path: spack-src # Where to clone Spack      # - name: Get Spack

      - if: ${{ matrix.backend.runtime == 'cpu' }}
        name: Install (CPU)
        shell: spack-bash {0}
        run: |
          spack repo add --name bench_pkgs https://github.com/ukri-bench/spack-packages.git bench_pkgs
          spack env create . https://raw.githubusercontent.com/ukri-bench/spack-configs/refs/heads/main/configs/gh-actions/gh-actions-env.yml
          # spack env create . spack-configs/gh-actions-env.yaml
          spack -e . install -j 4 --use-buildcache=package:never,dependencies:auto --add bench-dolfinx

      - if: ${{ matrix.backend.runtime == 'cuda' || matrix.backend.runtime == 'rocm' }}
        name: Install (GPU)
        shell: spack-bash {0}
        run: |
          spack repo add --name bench_pkgs https://github.com/ukri-bench/spack-packages.git bench_pkgs
          spack env create . spack-configs/gh-actions-env.yaml
          spack -e . install -j 4 --use-buildcache=package:never,dependencies:auto --add bench-dolfinx+${{ matrix.backend.runtime }} ${{ matrix.backend.driver }}

      - name: Push packages and update index
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: spack -e . buildcache push --base-image ubuntu:24.04 --update-index local-buildcache
        if: ${{ !cancelled() }}
